# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c1270b8a59d28c857ff4e644d468779484c27e6dcdc3e7379c1a824bc77becb6d8c4d08bd505ab3535189324cf6b00e81b0fe67166ab048e44e950cd7f3082c

test:
  secret_key_base: 3c1270b8a59d28c857ff4e644d468779484c27e6dcdc3e7379c1a824bc77becb6d8c4d08bd505ab3535189324cf6b00e81b0fe67166ab048e44e950cd7f3082c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
